version: '3.4'

networks:
  cms-dev:
    driver: bridge

services:
  cms:
    image: cms:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=cms_db;username=dbUser;password=pass"
    networks:
      - cms-dev
  
  postgres_image:
    image: postgres:latest
    ports:
      - "49597:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "dbUser"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "cms_db"
    networks:
      - cms-dev
volumes:
  db_volume:
         
    
     